const USER_INFO_KEY = "user_Info_key";
const LOGIN = {
   REQUEST: "LOGIN_REQUEST",
   SUCCESS: "LOGIN_SUCCESS",
   FAILURE: "LOGIN_FAILURE",
   CLEAR_ERRORS: "CLEAR_ERRORS"
};

const SIGNUP = {
   REQUEST: "SIGNUP_REQUEST",
   SUCCESS: "SIGNUP_SUCCESS",
   FAILURE: "SIGNUP_FAILURE",
   CLEAR_ERRORS: "CLEAR_ERRORS"
};

export { USER_INFO_KEY, LOGIN, SIGNUP };
